//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabNetStats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GabNetStats.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average emission speed.
        /// </summary>
        internal static string str_AvgEmissionSpeed {
            get {
                return ResourceManager.GetString("str_AvgEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average reception speed.
        /// </summary>
        internal static string str_AvgReceptionSpeed {
            get {
                return ResourceManager.GetString("str_AvgReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit.
        /// </summary>
        internal static string str_bit {
            get {
                return ResourceManager.GetString("str_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string str_Bytes {
            get {
                return ResourceManager.GetString("str_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in GabNetStats. We are sorry for this inconvenience and are looking to correct the problem as soon as possible.
        ///Below is displayed the cause of the error that you can send to the developer using a screenshot :.
        /// </summary>
        internal static string str_ErrorCrash {
            get {
                return ResourceManager.GetString("str_ErrorCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gbit.
        /// </summary>
        internal static string str_Gbit {
            get {
                return ResourceManager.GetString("str_Gbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        internal static string str_GiB {
            get {
                return ResourceManager.GetString("str_GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in statistics.
        /// </summary>
        internal static string str_IncludeInStatistics {
            get {
                return ResourceManager.GetString("str_IncludeInStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kbit.
        /// </summary>
        internal static string str_Kbit {
            get {
                return ResourceManager.GetString("str_Kbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        internal static string str_KiB {
            get {
                return ResourceManager.GetString("str_KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbit.
        /// </summary>
        internal static string str_Mbit {
            get {
                return ResourceManager.GetString("str_Mbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        internal static string str_MiB {
            get {
                return ResourceManager.GetString("str_MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string str_No {
            get {
                return ResourceManager.GetString("str_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IP available.
        /// </summary>
        internal static string str_NoIpAvailable {
            get {
                return ResourceManager.GetString("str_NoIpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string str_None {
            get {
                return ResourceManager.GetString("str_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string str_NotConnected {
            get {
                return ResourceManager.GetString("str_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous emission speed.
        /// </summary>
        internal static string str_RawEmissionSpeed {
            get {
                return ResourceManager.GetString("str_RawEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous reception speed.
        /// </summary>
        internal static string str_RawReceptionSpeed {
            get {
                return ResourceManager.GetString("str_RawReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string str_Received {
            get {
                return ResourceManager.GetString("str_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string str_Sent {
            get {
                return ResourceManager.GetString("str_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string str_Statistics {
            get {
                return ResourceManager.GetString("str_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tbit.
        /// </summary>
        internal static string str_Tbit {
            get {
                return ResourceManager.GetString("str_Tbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        internal static string str_TiB {
            get {
                return ResourceManager.GetString("str_TiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported.
        /// </summary>
        internal static string str_Unsupported {
            get {
                return ResourceManager.GetString("str_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value below 50ms could possibly use too much CPU !.
        /// </summary>
        internal static string str_WarningContent {
            get {
                return ResourceManager.GetString("str_WarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface is currently selected for statistics : it means that the icon in the notification area and the notification window will no longer be updated !.
        /// </summary>
        internal static string str_WarningNoInterfaceSelected {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string str_WarningNoInterfaceSelectedCaption {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning !.
        /// </summary>
        internal static string str_WarningTitle {
            get {
                return ResourceManager.GetString("str_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string str_Yes {
            get {
                return ResourceManager.GetString("str_Yes", resourceCulture);
            }
        }
    }
}
