//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabNetStats {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GabNetStats.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average emission speed.
        /// </summary>
        internal static string str_AvgEmissionSpeed {
            get {
                return ResourceManager.GetString("str_AvgEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average reception speed.
        /// </summary>
        internal static string str_AvgReceptionSpeed {
            get {
                return ResourceManager.GetString("str_AvgReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bit.
        /// </summary>
        internal static string str_bit {
            get {
                return ResourceManager.GetString("str_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bytes.
        /// </summary>
        internal static string str_Bytes {
            get {
                return ResourceManager.GetString("str_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred in GabNetStats. We are sorry for this inconvenience and are looking to correct the problem as soon as possible.
        ///Below is displayed the cause of the error that you can send to the developer using a screenshot :.
        /// </summary>
        internal static string str_ErrorCrash {
            get {
                return ResourceManager.GetString("str_ErrorCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gbit.
        /// </summary>
        internal static string str_Gbit {
            get {
                return ResourceManager.GetString("str_Gbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GiB.
        /// </summary>
        internal static string str_GiB {
            get {
                return ResourceManager.GetString("str_GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Include in statistics.
        /// </summary>
        internal static string str_IncludeInStatistics {
            get {
                return ResourceManager.GetString("str_IncludeInStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kbit.
        /// </summary>
        internal static string str_Kbit {
            get {
                return ResourceManager.GetString("str_Kbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KiB.
        /// </summary>
        internal static string str_KiB {
            get {
                return ResourceManager.GetString("str_KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mbit.
        /// </summary>
        internal static string str_Mbit {
            get {
                return ResourceManager.GetString("str_Mbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MiB.
        /// </summary>
        internal static string str_MiB {
            get {
                return ResourceManager.GetString("str_MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string str_No {
            get {
                return ResourceManager.GetString("str_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No IP available.
        /// </summary>
        internal static string str_NoIpAvailable {
            get {
                return ResourceManager.GetString("str_NoIpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string str_None {
            get {
                return ResourceManager.GetString("str_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This feature is not available in this version of Windows!.
        /// </summary>
        internal static string str_NotAvailableWinver {
            get {
                return ResourceManager.GetString("str_NotAvailableWinver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not connected.
        /// </summary>
        internal static string str_NotConnected {
            get {
                return ResourceManager.GetString("str_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instantaneous emission speed.
        /// </summary>
        internal static string str_RawEmissionSpeed {
            get {
                return ResourceManager.GetString("str_RawEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instantaneous reception speed.
        /// </summary>
        internal static string str_RawReceptionSpeed {
            get {
                return ResourceManager.GetString("str_RawReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Received.
        /// </summary>
        internal static string str_Received {
            get {
                return ResourceManager.GetString("str_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sent.
        /// </summary>
        internal static string str_Sent {
            get {
                return ResourceManager.GetString("str_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        internal static string str_Statistics {
            get {
                return ResourceManager.GetString("str_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tbit.
        /// </summary>
        internal static string str_Tbit {
            get {
                return ResourceManager.GetString("str_Tbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TiB.
        /// </summary>
        internal static string str_TiB {
            get {
                return ResourceManager.GetString("str_TiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported.
        /// </summary>
        internal static string str_Unsupported {
            get {
                return ResourceManager.GetString("str_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A value below 50ms could possibly use too much CPU !.
        /// </summary>
        internal static string str_WarningContent {
            get {
                return ResourceManager.GetString("str_WarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No network interface is currently selected for statistics : it means that the icon in the notification area and the notification window will no longer be updated !.
        /// </summary>
        internal static string str_WarningNoInterfaceSelected {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string str_WarningNoInterfaceSelectedCaption {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning !.
        /// </summary>
        internal static string str_WarningTitle {
            get {
                return ResourceManager.GetString("str_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string str_Yes {
            get {
                return ResourceManager.GetString("str_Yes", resourceCulture);
            }
        }
    }
}
