//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabNetStats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GabNetStats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon active_blue_blue {
            get {
                object obj = ResourceManager.GetObject("active_blue_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_blue_green {
            get {
                object obj = ResourceManager.GetObject("active_blue_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_blue_orange {
            get {
                object obj = ResourceManager.GetObject("active_blue_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_blue_red {
            get {
                object obj = ResourceManager.GetObject("active_blue_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_blue_yellow {
            get {
                object obj = ResourceManager.GetObject("active_blue_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_green_blue {
            get {
                object obj = ResourceManager.GetObject("active_green_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_green_green {
            get {
                object obj = ResourceManager.GetObject("active_green_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_green_orange {
            get {
                object obj = ResourceManager.GetObject("active_green_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_green_red {
            get {
                object obj = ResourceManager.GetObject("active_green_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_green_yellow {
            get {
                object obj = ResourceManager.GetObject("active_green_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_orange_blue {
            get {
                object obj = ResourceManager.GetObject("active_orange_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_orange_green {
            get {
                object obj = ResourceManager.GetObject("active_orange_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_orange_orange {
            get {
                object obj = ResourceManager.GetObject("active_orange_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_orange_red {
            get {
                object obj = ResourceManager.GetObject("active_orange_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_orange_yellow {
            get {
                object obj = ResourceManager.GetObject("active_orange_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_red_blue {
            get {
                object obj = ResourceManager.GetObject("active_red_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_red_green {
            get {
                object obj = ResourceManager.GetObject("active_red_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_red_orange {
            get {
                object obj = ResourceManager.GetObject("active_red_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_red_red {
            get {
                object obj = ResourceManager.GetObject("active_red_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_red_yellow {
            get {
                object obj = ResourceManager.GetObject("active_red_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_yellow_blue {
            get {
                object obj = ResourceManager.GetObject("active_yellow_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_yellow_green {
            get {
                object obj = ResourceManager.GetObject("active_yellow_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_yellow_orange {
            get {
                object obj = ResourceManager.GetObject("active_yellow_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_yellow_red {
            get {
                object obj = ResourceManager.GetObject("active_yellow_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon active_yellow_yellow {
            get {
                object obj = ResourceManager.GetObject("active_yellow_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon deskadp_16x16 {
            get {
                object obj = ResourceManager.GetObject("deskadp_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireWallControlPanel_16x16 {
            get {
                object obj = ResourceManager.GetObject("FireWallControlPanel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageres_1013 {
            get {
                object obj = ResourceManager.GetObject("imageres_1013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon inactive {
            get {
                object obj = ResourceManager.GetObject("inactive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netcenter_16x16 {
            get {
                object obj = ResourceManager.GetObject("netcenter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon netshell_1612_16x16 {
            get {
                object obj = ResourceManager.GetObject("netshell_1612_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon netshell_1613_16x16 {
            get {
                object obj = ResourceManager.GetObject("netshell_1613_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netshell_16x16 {
            get {
                object obj = ResourceManager.GetObject("netshell_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon netshell_195 {
            get {
                object obj = ResourceManager.GetObject("netshell_195", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon netshell_IDI_CFI_TRAY_WIRED_WARNING {
            get {
                object obj = ResourceManager.GetObject("netshell_IDI_CFI_TRAY_WIRED_WARNING", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon NetworkIndicator {
            get {
                object obj = ResourceManager.GetObject("NetworkIndicator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap networkmap_1 {
            get {
                object obj = ResourceManager.GetObject("networkmap_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pnidui_2407_16x16 {
            get {
                object obj = ResourceManager.GetObject("pnidui_2407_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon receive_blue {
            get {
                object obj = ResourceManager.GetObject("receive_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon receive_green {
            get {
                object obj = ResourceManager.GetObject("receive_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon receive_orange {
            get {
                object obj = ResourceManager.GetObject("receive_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon receive_red {
            get {
                object obj = ResourceManager.GetObject("receive_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon receive_yellow {
            get {
                object obj = ResourceManager.GetObject("receive_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon send_blue {
            get {
                object obj = ResourceManager.GetObject("send_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon send_green {
            get {
                object obj = ResourceManager.GetObject("send_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon send_orange {
            get {
                object obj = ResourceManager.GetObject("send_orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon send_red {
            get {
                object obj = ResourceManager.GetObject("send_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon send_yellow {
            get {
                object obj = ResourceManager.GetObject("send_yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_icon_16x16 {
            get {
                object obj = ResourceManager.GetObject("settings_icon_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_18 {
            get {
                object obj = ResourceManager.GetObject("shell32_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wlanpref_101 {
            get {
                object obj = ResourceManager.GetObject("wlanpref_101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
